# permissions for end users to edit credentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentials-editor-role
rules:
- apiGroups:
  - alibaba.me.leonj
  resources:
  - credentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alibaba.me.leonj
  resources:
  - credentials/status
  verbs:
  - get
