# permissions for end users to view credentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: credentials-viewer-role
rules:
- apiGroups:
  - alibaba.me.leonj
  resources:
  - credentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alibaba.me.leonj
  resources:
  - credentials/status
  verbs:
  - get
