# permissions for end users to view vpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpc-viewer-role
rules:
- apiGroups:
  - alibaba.me.leonj
  resources:
  - vpcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alibaba.me.leonj
  resources:
  - vpcs/status
  verbs:
  - get
